/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/VendalWorkshop.glb -k -K -r 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WorkshopModel(props:any) {
  const { nodes, materials } = useGLTF('/VendalWorkshop.glb') as any
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh name="group1184716703" geometry={nodes.group1184716703.geometry} material={materials.mat17} />
        <mesh name="group987980187" geometry={nodes.group987980187.geometry} material={materials.mat18} />
        <group name="group1819965688">
          <mesh name="mesh1819965688" geometry={nodes.mesh1819965688.geometry} material={materials.mat18} />
          <mesh name="mesh1819965688_1" geometry={nodes.mesh1819965688_1.geometry} material={materials.mat13} />
          <mesh name="mesh1819965688_2" geometry={nodes.mesh1819965688_2.geometry} material={materials.mat19} />
        </group>
        <group name="group259666405">
          <mesh name="mesh259666405" geometry={nodes.mesh259666405.geometry} material={materials.mat18} />
          <mesh name="mesh259666405_1" geometry={nodes.mesh259666405_1.geometry} material={materials.mat13} />
        </group>
        <mesh name="group1807314114" geometry={nodes.group1807314114.geometry} material={materials.mat16} />
        <mesh name="group177251386" geometry={nodes.group177251386.geometry} material={materials.mat16} />
        <mesh name="group92703077" geometry={nodes.group92703077.geometry} material={materials.mat22} />
        <mesh name="group1763104299" geometry={nodes.group1763104299.geometry} material={materials.mat18} />
        <group name="group337026695">
          <mesh name="mesh337026695" geometry={nodes.mesh337026695.geometry} material={materials.mat18} />
          <mesh name="mesh337026695_1" geometry={nodes.mesh337026695_1.geometry} material={materials.mat13} />
        </group>
        <mesh name="group1511929079" geometry={nodes.group1511929079.geometry} material={materials.mat22} />
        <mesh name="group526215780" geometry={nodes.group526215780.geometry} material={materials.mat22} />
        <mesh name="group2108269788" geometry={nodes.group2108269788.geometry} material={materials.mat22} />
        <mesh name="group1100343911" geometry={nodes.group1100343911.geometry} material={materials.mat16} />
        <mesh name="group196114910" geometry={nodes.group196114910.geometry} material={materials.mat13} />
        <mesh name="group1469415498" geometry={nodes.group1469415498.geometry} material={materials.mat13} />
        <mesh name="group1714775866" geometry={nodes.group1714775866.geometry} material={materials.mat13} />
        <group name="group1941141985">
          <mesh name="mesh1941141985" geometry={nodes.mesh1941141985.geometry} material={materials.mat22} />
          <mesh name="mesh1941141985_1" geometry={nodes.mesh1941141985_1.geometry} material={materials.mat17} />
          <mesh name="mesh1941141985_2" geometry={nodes.mesh1941141985_2.geometry} material={materials.mat21} />
        </group>
        <mesh name="group1056998046" geometry={nodes.group1056998046.geometry} material={materials.mat22} />
        <mesh name="group966136559" geometry={nodes.group966136559.geometry} material={materials.mat22} />
        <mesh name="group446171861" geometry={nodes.group446171861.geometry} material={materials.mat23} />
        <group name="group599849108">
          <mesh name="mesh599849108" geometry={nodes.mesh599849108.geometry} material={materials.mat20} />
          <mesh name="mesh599849108_1" geometry={nodes.mesh599849108_1.geometry} material={materials.mat19} />
        </group>
        <mesh name="group1854588575" geometry={nodes.group1854588575.geometry} material={materials.mat21} />
        <group name="group1423134592">
          <mesh name="mesh1423134592" geometry={nodes.mesh1423134592.geometry} material={materials.mat17} />
          <mesh name="mesh1423134592_1" geometry={nodes.mesh1423134592_1.geometry} material={materials.mat15} />
        </group>
        <group name="group1301697856">
          <mesh name="mesh1301697856" geometry={nodes.mesh1301697856.geometry} material={materials.mat1} />
          <mesh name="mesh1301697856_1" geometry={nodes.mesh1301697856_1.geometry} material={materials.mat21} />
          <mesh name="mesh1301697856_2" geometry={nodes.mesh1301697856_2.geometry} material={materials.mat17} />
        </group>
        <group name="group1295459945">
          <mesh name="mesh1295459945" geometry={nodes.mesh1295459945.geometry} material={materials.mat11} />
          <mesh name="mesh1295459945_1" geometry={nodes.mesh1295459945_1.geometry} material={materials.mat21} />
        </group>
        <group name="group1696156193">
          <mesh name="mesh1696156193" geometry={nodes.mesh1696156193.geometry} material={materials.mat21} />
          <mesh name="mesh1696156193_1" geometry={nodes.mesh1696156193_1.geometry} material={materials.mat20} />
          <mesh name="mesh1696156193_2" geometry={nodes.mesh1696156193_2.geometry} material={materials.mat17} />
        </group>
        <group name="group261235067">
          <mesh name="mesh261235067" geometry={nodes.mesh261235067.geometry} material={materials.mat20} />
          <mesh name="mesh261235067_1" geometry={nodes.mesh261235067_1.geometry} material={materials.mat21} />
        </group>
        <group name="group730930954">
          <mesh name="mesh730930954" geometry={nodes.mesh730930954.geometry} material={materials.mat21} />
          <mesh name="mesh730930954_1" geometry={nodes.mesh730930954_1.geometry} material={materials.mat1} />
        </group>
        <group name="group1703192743">
          <mesh name="mesh1703192743" geometry={nodes.mesh1703192743.geometry} material={materials.mat21} />
          <mesh name="mesh1703192743_1" geometry={nodes.mesh1703192743_1.geometry} material={materials.mat20} />
        </group>
        <group name="group1266423931">
          <mesh name="mesh1266423931" geometry={nodes.mesh1266423931.geometry} material={materials.mat21} />
          <mesh name="mesh1266423931_1" geometry={nodes.mesh1266423931_1.geometry} material={materials.mat1} />
        </group>
        <group name="group185882723">
          <mesh name="mesh185882723" geometry={nodes.mesh185882723.geometry} material={materials.mat21} />
          <mesh name="mesh185882723_1" geometry={nodes.mesh185882723_1.geometry} material={materials.mat20} />
        </group>
        <mesh name="group1581067494" geometry={nodes.group1581067494.geometry} material={materials.mat16} />
        <group name="group1688597213">
          <mesh name="mesh1688597213" geometry={nodes.mesh1688597213.geometry} material={materials.mat20} />
          <mesh name="mesh1688597213_1" geometry={nodes.mesh1688597213_1.geometry} material={materials.mat21} />
        </group>
        <group name="group1017789232">
          <mesh name="mesh1017789232" geometry={nodes.mesh1017789232.geometry} material={materials.mat21} />
          <mesh name="mesh1017789232_1" geometry={nodes.mesh1017789232_1.geometry} material={materials.mat11} />
        </group>
        <group name="group773497597">
          <mesh name="mesh773497597" geometry={nodes.mesh773497597.geometry} material={materials.mat21} />
          <mesh name="mesh773497597_1" geometry={nodes.mesh773497597_1.geometry} material={materials.mat20} />
        </group>
        <group name="group1124773544">
          <mesh name="mesh1124773544" geometry={nodes.mesh1124773544.geometry} material={materials.mat21} />
          <mesh name="mesh1124773544_1" geometry={nodes.mesh1124773544_1.geometry} material={materials.mat1} />
        </group>
        <group name="group2095273597">
          <mesh name="mesh2095273597" geometry={nodes.mesh2095273597.geometry} material={materials.mat21} />
          <mesh name="mesh2095273597_1" geometry={nodes.mesh2095273597_1.geometry} material={materials.mat11} />
        </group>
        <group name="group965151232">
          <mesh name="mesh965151232" geometry={nodes.mesh965151232.geometry} material={materials.mat21} />
          <mesh name="mesh965151232_1" geometry={nodes.mesh965151232_1.geometry} material={materials.mat11} />
        </group>
        <group name="group336546623">
          <mesh name="mesh336546623" geometry={nodes.mesh336546623.geometry} material={materials.mat22} />
          <mesh name="mesh336546623_1" geometry={nodes.mesh336546623_1.geometry} material={materials.mat14} />
        </group>
        <mesh name="group1743872181" geometry={nodes.group1743872181.geometry} material={materials.mat13} />
        <mesh name="group1552515826" geometry={nodes.group1552515826.geometry} material={materials.mat13} />
        <mesh name="group1819226584" geometry={nodes.group1819226584.geometry} material={materials.mat13} />
        <mesh name="group1431963884" geometry={nodes.group1431963884.geometry} material={materials.mat13} />
        <mesh name="group1238959292" geometry={nodes.group1238959292.geometry} material={materials.mat13} />
        <mesh name="group1857912791" geometry={nodes.group1857912791.geometry} material={materials.mat13} />
        <mesh name="group894288871" geometry={nodes.group894288871.geometry} material={materials.mat13} />
        <mesh name="group1557021028" geometry={nodes.group1557021028.geometry} material={materials.mat18} />
        <mesh name="group954819432" geometry={nodes.group954819432.geometry} material={materials.mat18} />
        <mesh name="group1290690196" geometry={nodes.group1290690196.geometry} material={materials.mat13} />
        <mesh name="group1536121849" geometry={nodes.group1536121849.geometry} material={materials.mat13} />
        <mesh name="group606757180" geometry={nodes.group606757180.geometry} material={materials.mat13} />
        <mesh name="group73971407" geometry={nodes.group73971407.geometry} material={materials.mat22} />
        <mesh name="group1040678360" geometry={nodes.group1040678360.geometry} material={materials.mat13} />
        <mesh name="group90722341" geometry={nodes.group90722341.geometry} material={materials.mat13} />
        <group name="group373007995">
          <mesh name="mesh373007995" geometry={nodes.mesh373007995.geometry} material={materials.mat13} />
          <mesh name="mesh373007995_1" geometry={nodes.mesh373007995_1.geometry} material={materials.mat18} />
        </group>
        <mesh name="group2040397977" geometry={nodes.group2040397977.geometry} material={materials.mat18} />
        <mesh name="group144190160" geometry={nodes.group144190160.geometry} material={materials.mat18} />
        <mesh name="group944985018" geometry={nodes.group944985018.geometry} material={materials.mat18} />
        <mesh name="group485381166" geometry={nodes.group485381166.geometry} material={materials.mat17} />
        <mesh name="group1031762774" geometry={nodes.group1031762774.geometry} material={materials.mat16} />
        <mesh name="group1599709707" geometry={nodes.group1599709707.geometry} material={materials.mat18} />
        <group name="group1795788254">
          <mesh name="mesh1795788254" geometry={nodes.mesh1795788254.geometry} material={materials.mat18} />
          <mesh name="mesh1795788254_1" geometry={nodes.mesh1795788254_1.geometry} material={materials.mat13} />
        </group>
        <mesh name="group1863503592" geometry={nodes.group1863503592.geometry} material={materials.mat18} />
        <mesh name="group362385284" geometry={nodes.group362385284.geometry} material={materials.mat18} />
        <mesh name="group398009161" geometry={nodes.group398009161.geometry} material={materials.mat17} />
        <mesh name="group1291429179" geometry={nodes.group1291429179.geometry} material={materials.mat18} />
        <mesh name="group1036221765" geometry={nodes.group1036221765.geometry} material={materials.mat18} />
        <mesh name="group836435734" geometry={nodes.group836435734.geometry} material={materials.mat18} />
        <mesh name="group101322500" geometry={nodes.group101322500.geometry} material={materials.mat18} />
        <mesh name="group1394797472" geometry={nodes.group1394797472.geometry} material={materials.mat18} />
        <mesh name="group395107489" geometry={nodes.group395107489.geometry} material={materials.mat13} />
        <mesh name="group975166849" geometry={nodes.group975166849.geometry} material={materials.mat13} />
        <mesh name="group39362121" geometry={nodes.group39362121.geometry} material={materials.mat13} />
        <mesh name="group852934428" geometry={nodes.group852934428.geometry} material={materials.mat13} />
        <mesh name="group384783331" geometry={nodes.group384783331.geometry} material={materials.mat13} />
        <mesh name="group1065398580" geometry={nodes.group1065398580.geometry} material={materials.mat13} />
        <mesh name="group590938307" geometry={nodes.group590938307.geometry} material={materials.mat13} />
        <mesh name="group49104271" geometry={nodes.group49104271.geometry} material={materials.mat13} />
        <mesh name="group1725386416" geometry={nodes.group1725386416.geometry} material={materials.mat13} />
        <group name="group187130821">
          <mesh name="mesh187130821" geometry={nodes.mesh187130821.geometry} material={materials.mat20} />
          <mesh name="mesh187130821_1" geometry={nodes.mesh187130821_1.geometry} material={materials.mat21} />
        </group>
        <mesh name="group1365582228" geometry={nodes.group1365582228.geometry} material={materials.mat21} />
        <group name="group1929373313">
          <mesh name="mesh1929373313" geometry={nodes.mesh1929373313.geometry} material={materials.mat21} />
          <mesh name="mesh1929373313_1" geometry={nodes.mesh1929373313_1.geometry} material={materials.mat22} />
          <mesh name="mesh1929373313_2" geometry={nodes.mesh1929373313_2.geometry} material={materials.mat17} />
        </group>
        <group name="group475958137">
          <mesh name="mesh475958137" geometry={nodes.mesh475958137.geometry} material={materials.mat20} />
          <mesh name="mesh475958137_1" geometry={nodes.mesh475958137_1.geometry} material={materials.mat19} />
        </group>
        <group name="group1163699737">
          <mesh name="mesh1163699737" geometry={nodes.mesh1163699737.geometry} material={materials.mat22} />
          <mesh name="mesh1163699737_1" geometry={nodes.mesh1163699737_1.geometry} material={materials.mat17} />
          <mesh name="mesh1163699737_2" geometry={nodes.mesh1163699737_2.geometry} material={materials.mat21} />
        </group>
        <mesh name="group403595213" geometry={nodes.group403595213.geometry} material={materials.mat21} />
        <mesh name="group1773523439" geometry={nodes.group1773523439.geometry} material={materials.mat21} />
        <mesh name="group1223871782" geometry={nodes.group1223871782.geometry} material={materials.mat21} />
        <mesh name="group64692380" geometry={nodes.group64692380.geometry} material={materials.mat21} />
        <mesh name="group21641648" geometry={nodes.group21641648.geometry} material={materials.mat21} />
        <mesh name="group1239758310" geometry={nodes.group1239758310.geometry} material={materials.mat21} />
        <mesh name="group1739072371" geometry={nodes.group1739072371.geometry} material={materials.mat21} />
        <mesh name="group399210981" geometry={nodes.group399210981.geometry} material={materials.mat21} />
        <mesh name="group571721780" geometry={nodes.group571721780.geometry} material={materials.mat21} />
        <mesh name="group1447263464" geometry={nodes.group1447263464.geometry} material={materials.mat21} />
        <mesh name="group654111799" geometry={nodes.group654111799.geometry} material={materials.mat21} />
        <mesh name="group262049209" geometry={nodes.group262049209.geometry} material={materials.mat21} />
        <mesh name="group625114459" geometry={nodes.group625114459.geometry} material={materials.mat21} />
        <mesh name="group1519807515" geometry={nodes.group1519807515.geometry} material={materials.mat21} />
        <mesh name="group816388643" geometry={nodes.group816388643.geometry} material={materials.mat17} />
        <mesh name="group260422066" geometry={nodes.group260422066.geometry} material={materials.mat18} />
        <mesh name="group513528595" geometry={nodes.group513528595.geometry} material={materials.mat21} />
        <mesh name="group785010165" geometry={nodes.group785010165.geometry} material={materials.mat18} />
        <mesh name="group666843748" geometry={nodes.group666843748.geometry} material={materials.mat13} />
        <mesh name="group1213824674" geometry={nodes.group1213824674.geometry} material={materials.mat13} />
        <mesh name="group1129443839" geometry={nodes.group1129443839.geometry} material={materials.mat16} />
        <mesh name="group1801202916" geometry={nodes.group1801202916.geometry} material={materials.mat13} />
        <mesh name="group1928254380" geometry={nodes.group1928254380.geometry} material={materials.mat13} />
        <mesh name="group914398037" geometry={nodes.group914398037.geometry} material={materials.mat13} />
        <mesh name="group1981541401" geometry={nodes.group1981541401.geometry} material={materials.mat13} />
        <mesh name="group539329900" geometry={nodes.group539329900.geometry} material={materials.mat13} />
        <mesh name="group1998161109" geometry={nodes.group1998161109.geometry} material={materials.mat16} />
        <mesh name="group324586929" geometry={nodes.group324586929.geometry} material={materials.mat13} />
        <mesh name="group265183981" geometry={nodes.group265183981.geometry} material={materials.mat13} />
        <mesh name="group318348928" geometry={nodes.group318348928.geometry} material={materials.mat13} />
        <group name="group1539503804">
          <mesh name="mesh1539503804" geometry={nodes.mesh1539503804.geometry} material={materials.mat17} />
          <mesh name="mesh1539503804_1" geometry={nodes.mesh1539503804_1.geometry} material={materials.mat23} />
        </group>
        <group name="group2022069560">
          <mesh name="mesh2022069560" geometry={nodes.mesh2022069560.geometry} material={materials.mat23} />
          <mesh name="mesh2022069560_1" geometry={nodes.mesh2022069560_1.geometry} material={materials.mat17} />
        </group>
        <mesh name="group1592160675" geometry={nodes.group1592160675.geometry} material={materials.mat21} />
        <mesh name="group2013451613" geometry={nodes.group2013451613.geometry} material={materials.mat21} />
        <mesh name="group409985533" geometry={nodes.group409985533.geometry} material={materials.mat16} />
        <mesh name="group2053722093" geometry={nodes.group2053722093.geometry} material={materials.mat16} />
        <mesh name="group417629898" geometry={nodes.group417629898.geometry} material={materials.mat13} />
        <mesh name="group149216813" geometry={nodes.group149216813.geometry} material={materials.mat13} />
        <mesh name="group22866469" geometry={nodes.group22866469.geometry} material={materials.mat13} />
        <mesh name="group339383657" geometry={nodes.group339383657.geometry} material={materials.mat13} />
        <mesh name="group592801492" geometry={nodes.group592801492.geometry} material={materials.mat13} />
        <mesh name="group1908947530" geometry={nodes.group1908947530.geometry} material={materials.mat13} />
        <mesh name="group2056848520" geometry={nodes.group2056848520.geometry} material={materials.mat13} />
        <mesh name="group2097243166" geometry={nodes.group2097243166.geometry} material={materials.mat13} />
        <mesh name="group118993706" geometry={nodes.group118993706.geometry} material={materials.mat13} />
        <mesh name="group1305653608" geometry={nodes.group1305653608.geometry} material={materials.mat13} />
        <mesh name="group1157935928" geometry={nodes.group1157935928.geometry} material={materials.mat13} />
        <mesh name="group994914109" geometry={nodes.group994914109.geometry} material={materials.mat13} />
        <mesh name="group482177715" geometry={nodes.group482177715.geometry} material={materials.mat13} />
        <mesh name="group1899386574" geometry={nodes.group1899386574.geometry} material={materials.mat5} />
        <mesh name="group449663761" geometry={nodes.group449663761.geometry} material={materials.mat13} />
        <mesh name="group480884222" geometry={nodes.group480884222.geometry} material={materials.mat13} />
        <mesh name="group482146617" geometry={nodes.group482146617.geometry} material={materials.mat13} />
        <mesh name="group482143986" geometry={nodes.group482143986.geometry} material={materials.mat13} />
        <mesh name="group1861495927" geometry={nodes.group1861495927.geometry} material={materials.mat22} />
        <mesh name="group1288222834" geometry={nodes.group1288222834.geometry} material={materials.mat24} />
        <mesh name="group1556157741" geometry={nodes.group1556157741.geometry} material={materials.mat16} />
        <group name="group1958308568">
          <mesh name="mesh1958308568" geometry={nodes.mesh1958308568.geometry} material={materials.mat1} />
          <mesh name="mesh1958308568_1" geometry={nodes.mesh1958308568_1.geometry} material={materials.mat21} />
        </group>
        <mesh name="group110164448" geometry={nodes.group110164448.geometry} material={materials.mat17} />
        <group name="group201399583">
          <mesh name="mesh201399583" geometry={nodes.mesh201399583.geometry} material={materials.mat21} />
          <mesh name="mesh201399583_1" geometry={nodes.mesh201399583_1.geometry} material={materials.mat16} />
          <mesh name="mesh201399583_2" geometry={nodes.mesh201399583_2.geometry} material={materials.mat8} />
        </group>
        <mesh name="group2075641627" geometry={nodes.group2075641627.geometry} material={materials.mat17} />
        <group name="group2105230691">
          <mesh name="mesh2105230691" geometry={nodes.mesh2105230691.geometry} material={materials.mat17} />
          <mesh name="mesh2105230691_1" geometry={nodes.mesh2105230691_1.geometry} material={materials.mat16} />
          <mesh name="mesh2105230691_2" geometry={nodes.mesh2105230691_2.geometry} material={materials.mat21} />
          <mesh name="mesh2105230691_3" geometry={nodes.mesh2105230691_3.geometry} material={materials.mat24} />
        </group>
        <mesh name="group1344221060" geometry={nodes.group1344221060.geometry} material={materials.mat17} />
        <group name="group2091374559">
          <mesh name="mesh2091374559" geometry={nodes.mesh2091374559.geometry} material={materials.mat17} />
          <mesh name="mesh2091374559_1" geometry={nodes.mesh2091374559_1.geometry} material={materials.mat21} />
          <mesh name="mesh2091374559_2" geometry={nodes.mesh2091374559_2.geometry} material={materials.mat23} />
          <mesh name="mesh2091374559_3" geometry={nodes.mesh2091374559_3.geometry} material={materials.mat16} />
          <mesh name="mesh2091374559_4" geometry={nodes.mesh2091374559_4.geometry} material={materials.mat7} />
          <mesh name="mesh2091374559_5" geometry={nodes.mesh2091374559_5.geometry} material={materials.mat12} />
          <mesh name="mesh2091374559_6" geometry={nodes.mesh2091374559_6.geometry} material={materials.mat4} />
        </group>
        <group name="group788008164">
          <mesh name="mesh788008164" geometry={nodes.mesh788008164.geometry} material={materials.mat4} />
          <mesh name="mesh788008164_1" geometry={nodes.mesh788008164_1.geometry} material={materials.mat21} />
          <mesh name="mesh788008164_2" geometry={nodes.mesh788008164_2.geometry} material={materials.mat17} />
          <mesh name="mesh788008164_3" geometry={nodes.mesh788008164_3.geometry} material={materials.mat16} />
          <mesh name="mesh788008164_4" geometry={nodes.mesh788008164_4.geometry} material={materials.mat23} />
          <mesh name="mesh788008164_5" geometry={nodes.mesh788008164_5.geometry} material={materials.mat7} />
          <mesh name="mesh788008164_6" geometry={nodes.mesh788008164_6.geometry} material={materials.mat12} />
        </group>
        <mesh name="group798143844" geometry={nodes.group798143844.geometry} material={materials.mat13} />
        <mesh name="group1281142923" geometry={nodes.group1281142923.geometry} material={materials.mat13} />
        <mesh name="group726125833" geometry={nodes.group726125833.geometry} material={materials.mat13} />
        <mesh name="group1023197535" geometry={nodes.group1023197535.geometry} material={materials.mat13} />
        <mesh name="group949799839" geometry={nodes.group949799839.geometry} material={materials.mat13} />
        <mesh name="group247746533" geometry={nodes.group247746533.geometry} material={materials.mat13} />
        <mesh name="group1095370598" geometry={nodes.group1095370598.geometry} material={materials.mat13} />
        <mesh name="group1329214417" geometry={nodes.group1329214417.geometry} material={materials.mat13} />
        <mesh name="group1118272074" geometry={nodes.group1118272074.geometry} material={materials.mat13} />
        <mesh name="group1392307038" geometry={nodes.group1392307038.geometry} material={materials.mat13} />
        <group name="group2067733323">
          <mesh name="mesh2067733323" geometry={nodes.mesh2067733323.geometry} material={materials.mat16} />
          <mesh name="mesh2067733323_1" geometry={nodes.mesh2067733323_1.geometry} material={materials.mat17} />
        </group>
        <mesh name="group1259991768" geometry={nodes.group1259991768.geometry} material={materials.mat16} />
        <mesh name="group576403789" geometry={nodes.group576403789.geometry} material={materials.mat16} />
        <mesh name="group562186971" geometry={nodes.group562186971.geometry} material={materials.mat16} />
        <mesh name="group835594193" geometry={nodes.group835594193.geometry} material={materials.mat16} />
        <mesh name="group830030252" geometry={nodes.group830030252.geometry} material={materials.mat17} />
        <mesh name="group657624877" geometry={nodes.group657624877.geometry} material={materials.mat16} />
        <mesh name="group1705120454" geometry={nodes.group1705120454.geometry} material={materials.mat17} />
        <mesh name="group388597313" geometry={nodes.group388597313.geometry} material={materials.mat17} />
        <mesh name="group221327672" geometry={nodes.group221327672.geometry} material={materials.mat16} />
        <mesh name="group1398417447" geometry={nodes.group1398417447.geometry} material={materials.mat17} />
        <mesh name="group974214848" geometry={nodes.group974214848.geometry} material={materials.mat17} />
        <mesh name="group528036490" geometry={nodes.group528036490.geometry} material={materials.mat16} />
        <mesh name="group1433687755" geometry={nodes.group1433687755.geometry} material={materials.mat17} />
        <mesh name="group21230822" geometry={nodes.group21230822.geometry} material={materials.mat17} />
        <mesh name="group627934623" geometry={nodes.group627934623.geometry} material={materials.mat16} />
        <mesh name="group1049834771" geometry={nodes.group1049834771.geometry} material={materials.mat17} />
        <mesh name="group231096650" geometry={nodes.group231096650.geometry} material={materials.mat17} />
        <mesh name="group526592418" geometry={nodes.group526592418.geometry} material={materials.mat16} />
        <mesh name="group523132470" geometry={nodes.group523132470.geometry} material={materials.mat20} />
        <mesh name="group614186588" geometry={nodes.group614186588.geometry} material={materials.mat20} />
        <mesh name="group1331359260" geometry={nodes.group1331359260.geometry} material={materials.mat17} />
        <mesh name="group1253954340" geometry={nodes.group1253954340.geometry} material={materials.mat23} />
        <group name="group975002159">
          <mesh name="mesh975002159" geometry={nodes.mesh975002159.geometry} material={materials.mat16} />
          <mesh name="mesh975002159_1" geometry={nodes.mesh975002159_1.geometry} material={materials.mat22} />
        </group>
        <group name="group1048239680">
          <mesh name="mesh1048239680" geometry={nodes.mesh1048239680.geometry} material={materials.mat16} />
          <mesh name="mesh1048239680_1" geometry={nodes.mesh1048239680_1.geometry} material={materials.mat17} />
          <mesh name="mesh1048239680_2" geometry={nodes.mesh1048239680_2.geometry} material={materials.mat14} />
          <mesh name="mesh1048239680_3" geometry={nodes.mesh1048239680_3.geometry} material={materials.mat24} />
        </group>
        <group name="group965971404">
          <mesh name="mesh965971404" geometry={nodes.mesh965971404.geometry} material={materials.mat17} />
          <mesh name="mesh965971404_1" geometry={nodes.mesh965971404_1.geometry} material={materials.mat16} />
          <mesh name="mesh965971404_2" geometry={nodes.mesh965971404_2.geometry} material={materials.mat12} />
        </group>
        <group name="group722914409">
          <mesh name="mesh722914409" geometry={nodes.mesh722914409.geometry} material={materials.mat22} />
          <mesh name="mesh722914409_1" geometry={nodes.mesh722914409_1.geometry} material={materials.mat17} />
        </group>
        <group name="group965507046">
          <mesh name="mesh965507046" geometry={nodes.mesh965507046.geometry} material={materials.mat17} />
          <mesh name="mesh965507046_1" geometry={nodes.mesh965507046_1.geometry} material={materials.mat16} />
        </group>
        <group name="group1018027720">
          <mesh name="mesh1018027720" geometry={nodes.mesh1018027720.geometry} material={materials.mat17} />
          <mesh name="mesh1018027720_1" geometry={nodes.mesh1018027720_1.geometry} material={materials.mat15} />
        </group>
        <group name="group1429421874">
          <mesh name="mesh1429421874" geometry={nodes.mesh1429421874.geometry} material={materials.mat15} />
          <mesh name="mesh1429421874_1" geometry={nodes.mesh1429421874_1.geometry} material={materials.mat17} />
        </group>
        <group name="group99714018">
          <mesh name="mesh99714018" geometry={nodes.mesh99714018.geometry} material={materials.mat22} />
          <mesh name="mesh99714018_1" geometry={nodes.mesh99714018_1.geometry} material={materials.mat16} />
          <mesh name="mesh99714018_2" geometry={nodes.mesh99714018_2.geometry} material={materials.mat17} />
        </group>
        <group name="group415518403">
          <mesh name="mesh415518403" geometry={nodes.mesh415518403.geometry} material={materials.mat22} />
          <mesh name="mesh415518403_1" geometry={nodes.mesh415518403_1.geometry} material={materials.mat16} />
        </group>
        <mesh name="group1544649000" geometry={nodes.group1544649000.geometry} material={materials.mat20} />
        <group name="group1794454191">
          <mesh name="mesh1794454191" geometry={nodes.mesh1794454191.geometry} material={materials.mat16} />
          <mesh name="mesh1794454191_1" geometry={nodes.mesh1794454191_1.geometry} material={materials.mat17} />
          <mesh name="mesh1794454191_2" geometry={nodes.mesh1794454191_2.geometry} material={materials.mat12} />
        </group>
        <group name="group380460076">
          <mesh name="mesh380460076" geometry={nodes.mesh380460076.geometry} material={materials.mat17} />
          <mesh name="mesh380460076_1" geometry={nodes.mesh380460076_1.geometry} material={materials.mat15} />
        </group>
        <group name="group1615416689">
          <mesh name="mesh1615416689" geometry={nodes.mesh1615416689.geometry} material={materials.mat17} />
          <mesh name="mesh1615416689_1" geometry={nodes.mesh1615416689_1.geometry} material={materials.mat24} />
          <mesh name="mesh1615416689_2" geometry={nodes.mesh1615416689_2.geometry} material={materials.mat10} />
        </group>
        <group name="group1079008815">
          <mesh name="mesh1079008815" geometry={nodes.mesh1079008815.geometry} material={materials.mat17} />
          <mesh name="mesh1079008815_1" geometry={nodes.mesh1079008815_1.geometry} material={materials.mat2} />
          <mesh name="mesh1079008815_2" geometry={nodes.mesh1079008815_2.geometry} material={materials.mat14} />
          <mesh name="mesh1079008815_3" geometry={nodes.mesh1079008815_3.geometry} material={materials.mat16} />
        </group>
        <group name="group1451214769">
          <mesh name="mesh1451214769" geometry={nodes.mesh1451214769.geometry} material={materials.mat16} />
          <mesh name="mesh1451214769_1" geometry={nodes.mesh1451214769_1.geometry} material={materials.mat14} />
          <mesh name="mesh1451214769_2" geometry={nodes.mesh1451214769_2.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1095894712" geometry={nodes.group1095894712.geometry} material={materials.mat16} />
        <group name="group1024795164">
          <mesh name="mesh1024795164" geometry={nodes.mesh1024795164.geometry} material={materials.mat16} />
          <mesh name="mesh1024795164_1" geometry={nodes.mesh1024795164_1.geometry} material={materials.mat18} />
          <mesh name="mesh1024795164_2" geometry={nodes.mesh1024795164_2.geometry} material={materials.mat13} />
        </group>
        <mesh name="group210054819" geometry={nodes.group210054819.geometry} material={materials.mat17} />
        <group name="group286800131">
          <mesh name="mesh286800131" geometry={nodes.mesh286800131.geometry} material={materials.mat17} />
          <mesh name="mesh286800131_1" geometry={nodes.mesh286800131_1.geometry} material={materials.mat16} />
          <mesh name="mesh286800131_2" geometry={nodes.mesh286800131_2.geometry} material={materials.mat2} />
          <mesh name="mesh286800131_3" geometry={nodes.mesh286800131_3.geometry} material={materials.mat24} />
        </group>
        <mesh name="group1713186528" geometry={nodes.group1713186528.geometry} material={materials.mat16} />
        <group name="group1482947389">
          <mesh name="mesh1482947389" geometry={nodes.mesh1482947389.geometry} material={materials.mat16} />
          <mesh name="mesh1482947389_1" geometry={nodes.mesh1482947389_1.geometry} material={materials.mat24} />
          <mesh name="mesh1482947389_2" geometry={nodes.mesh1482947389_2.geometry} material={materials.mat12} />
          <mesh name="mesh1482947389_3" geometry={nodes.mesh1482947389_3.geometry} material={materials.mat17} />
        </group>
        <group name="group166672997">
          <mesh name="mesh166672997" geometry={nodes.mesh166672997.geometry} material={materials.mat17} />
          <mesh name="mesh166672997_1" geometry={nodes.mesh166672997_1.geometry} material={materials.mat16} />
          <mesh name="mesh166672997_2" geometry={nodes.mesh166672997_2.geometry} material={materials.mat24} />
          <mesh name="mesh166672997_3" geometry={nodes.mesh166672997_3.geometry} material={materials.mat12} />
        </group>
        <group name="group1838156658">
          <mesh name="mesh1838156658" geometry={nodes.mesh1838156658.geometry} material={materials.mat11} />
          <mesh name="mesh1838156658_1" geometry={nodes.mesh1838156658_1.geometry} material={materials.mat21} />
          <mesh name="mesh1838156658_2" geometry={nodes.mesh1838156658_2.geometry} material={materials.mat20} />
        </group>
        <group name="group80340542">
          <mesh name="mesh80340542" geometry={nodes.mesh80340542.geometry} material={materials.mat20} />
          <mesh name="mesh80340542_1" geometry={nodes.mesh80340542_1.geometry} material={materials.mat19} />
        </group>
        <group name="group1329093171">
          <mesh name="mesh1329093171" geometry={nodes.mesh1329093171.geometry} material={materials.mat16} />
          <mesh name="mesh1329093171_1" geometry={nodes.mesh1329093171_1.geometry} material={materials.mat15} />
        </group>
        <group name="group1477842501">
          <mesh name="mesh1477842501" geometry={nodes.mesh1477842501.geometry} material={materials.mat15} />
          <mesh name="mesh1477842501_1" geometry={nodes.mesh1477842501_1.geometry} material={materials.mat17} />
          <mesh name="mesh1477842501_2" geometry={nodes.mesh1477842501_2.geometry} material={materials.mat21} />
        </group>
        <mesh name="group757955278" geometry={nodes.group757955278.geometry} material={materials.mat21} />
        <mesh name="group1046072727" geometry={nodes.group1046072727.geometry} material={materials.mat17} />
        <group name="group1994108841">
          <mesh name="mesh1994108841" geometry={nodes.mesh1994108841.geometry} material={materials.mat17} />
          <mesh name="mesh1994108841_1" geometry={nodes.mesh1994108841_1.geometry} material={materials.mat24} />
          <mesh name="mesh1994108841_2" geometry={nodes.mesh1994108841_2.geometry} material={materials.mat10} />
        </group>
        <group name="group1527169260">
          <mesh name="mesh1527169260" geometry={nodes.mesh1527169260.geometry} material={materials.mat16} />
          <mesh name="mesh1527169260_1" geometry={nodes.mesh1527169260_1.geometry} material={materials.mat15} />
        </group>
        <mesh name="group1293440205" geometry={nodes.group1293440205.geometry} material={materials.mat17} />
        <mesh name="group1170003094" geometry={nodes.group1170003094.geometry} material={materials.mat17} />
        <mesh name="group1132960755" geometry={nodes.group1132960755.geometry} material={materials.mat17} />
        <group name="group1203974772">
          <mesh name="mesh1203974772" geometry={nodes.mesh1203974772.geometry} material={materials.mat24} />
          <mesh name="mesh1203974772_1" geometry={nodes.mesh1203974772_1.geometry} material={materials.mat15} />
          <mesh name="mesh1203974772_2" geometry={nodes.mesh1203974772_2.geometry} material={materials.mat22} />
        </group>
        <group name="group1105171987">
          <mesh name="mesh1105171987" geometry={nodes.mesh1105171987.geometry} material={materials.mat24} />
          <mesh name="mesh1105171987_1" geometry={nodes.mesh1105171987_1.geometry} material={materials.mat19} />
          <mesh name="mesh1105171987_2" geometry={nodes.mesh1105171987_2.geometry} material={materials.mat21} />
        </group>
        <group name="group1209339750">
          <mesh name="mesh1209339750" geometry={nodes.mesh1209339750.geometry} material={materials.mat9} />
          <mesh name="mesh1209339750_1" geometry={nodes.mesh1209339750_1.geometry} material={materials.mat20} />
        </group>
        <mesh name="group568371142" geometry={nodes.group568371142.geometry} material={materials.mat9} />
        <group name="group80423347">
          <mesh name="mesh80423347" geometry={nodes.mesh80423347.geometry} material={materials.mat9} />
          <mesh name="mesh80423347_1" geometry={nodes.mesh80423347_1.geometry} material={materials.mat24} />
          <mesh name="mesh80423347_2" geometry={nodes.mesh80423347_2.geometry} material={materials.mat19} />
          <mesh name="mesh80423347_3" geometry={nodes.mesh80423347_3.geometry} material={materials.mat21} />
          <mesh name="mesh80423347_4" geometry={nodes.mesh80423347_4.geometry} material={materials.mat20} />
        </group>
        <group name="group1943887625">
          <mesh name="mesh1943887625" geometry={nodes.mesh1943887625.geometry} material={materials.mat17} />
          <mesh name="mesh1943887625_1" geometry={nodes.mesh1943887625_1.geometry} material={materials.mat22} />
        </group>
        <mesh name="group1097957595" geometry={nodes.group1097957595.geometry} material={materials.mat17} />
        <group name="group726155942">
          <mesh name="mesh726155942" geometry={nodes.mesh726155942.geometry} material={materials.mat24} />
          <mesh name="mesh726155942_1" geometry={nodes.mesh726155942_1.geometry} material={materials.mat15} />
          <mesh name="mesh726155942_2" geometry={nodes.mesh726155942_2.geometry} material={materials.mat19} />
        </group>
        <group name="group61219957">
          <mesh name="mesh61219957" geometry={nodes.mesh61219957.geometry} material={materials.mat17} />
          <mesh name="mesh61219957_1" geometry={nodes.mesh61219957_1.geometry} material={materials.mat16} />
        </group>
        <group name="group1604952410">
          <mesh name="mesh1604952410" geometry={nodes.mesh1604952410.geometry} material={materials.mat21} />
          <mesh name="mesh1604952410_1" geometry={nodes.mesh1604952410_1.geometry} material={materials.mat9} />
          <mesh name="mesh1604952410_2" geometry={nodes.mesh1604952410_2.geometry} material={materials.mat24} />
          <mesh name="mesh1604952410_3" geometry={nodes.mesh1604952410_3.geometry} material={materials.mat19} />
        </group>
        <group name="group418973208">
          <mesh name="mesh418973208" geometry={nodes.mesh418973208.geometry} material={materials.mat19} />
          <mesh name="mesh418973208_1" geometry={nodes.mesh418973208_1.geometry} material={materials.mat24} />
          <mesh name="mesh418973208_2" geometry={nodes.mesh418973208_2.geometry} material={materials.mat15} />
        </group>
        <mesh name="group389696598" geometry={nodes.group389696598.geometry} material={materials.mat17} />
        <group name="group850969638">
          <mesh name="mesh850969638" geometry={nodes.mesh850969638.geometry} material={materials.mat15} />
          <mesh name="mesh850969638_1" geometry={nodes.mesh850969638_1.geometry} material={materials.mat23} />
          <mesh name="mesh850969638_2" geometry={nodes.mesh850969638_2.geometry} material={materials.mat16} />
        </group>
        <mesh name="group1998789052" geometry={nodes.group1998789052.geometry} material={materials.mat17} />
        <mesh name="group466027787" geometry={nodes.group466027787.geometry} material={materials.mat17} />
        <group name="group1845611640">
          <mesh name="mesh1845611640" geometry={nodes.mesh1845611640.geometry} material={materials.mat24} />
          <mesh name="mesh1845611640_1" geometry={nodes.mesh1845611640_1.geometry} material={materials.mat7} />
          <mesh name="mesh1845611640_2" geometry={nodes.mesh1845611640_2.geometry} material={materials.mat23} />
        </group>
        <mesh name="group1035163510" geometry={nodes.group1035163510.geometry} material={materials.mat17} />
        <mesh name="group1443709309" geometry={nodes.group1443709309.geometry} material={materials.mat20} />
        <group name="group156274412">
          <mesh name="mesh156274412" geometry={nodes.mesh156274412.geometry} material={materials.mat22} />
          <mesh name="mesh156274412_1" geometry={nodes.mesh156274412_1.geometry} material={materials.mat17} />
        </group>
        <group name="group1014696620">
          <mesh name="mesh1014696620" geometry={nodes.mesh1014696620.geometry} material={materials.mat22} />
          <mesh name="mesh1014696620_1" geometry={nodes.mesh1014696620_1.geometry} material={materials.mat16} />
        </group>
        <mesh name="group762649891" geometry={nodes.group762649891.geometry} material={materials.mat17} />
        <group name="group1273082456">
          <mesh name="mesh1273082456" geometry={nodes.mesh1273082456.geometry} material={materials.mat17} />
          <mesh name="mesh1273082456_1" geometry={nodes.mesh1273082456_1.geometry} material={materials.mat15} />
        </group>
        <mesh name="group824595844" geometry={nodes.group824595844.geometry} material={materials.mat23} />
        <group name="group864974241">
          <mesh name="mesh864974241" geometry={nodes.mesh864974241.geometry} material={materials.mat23} />
          <mesh name="mesh864974241_1" geometry={nodes.mesh864974241_1.geometry} material={materials.mat15} />
          <mesh name="mesh864974241_2" geometry={nodes.mesh864974241_2.geometry} material={materials.mat17} />
        </group>
        <group name="group1349737614">
          <mesh name="mesh1349737614" geometry={nodes.mesh1349737614.geometry} material={materials.mat17} />
          <mesh name="mesh1349737614_1" geometry={nodes.mesh1349737614_1.geometry} material={materials.mat12} />
          <mesh name="mesh1349737614_2" geometry={nodes.mesh1349737614_2.geometry} material={materials.mat16} />
        </group>
        <mesh name="group1044813976" geometry={nodes.group1044813976.geometry} material={materials.mat17} />
        <group name="group734682161">
          <mesh name="mesh734682161" geometry={nodes.mesh734682161.geometry} material={materials.mat17} />
          <mesh name="mesh734682161_1" geometry={nodes.mesh734682161_1.geometry} material={materials.mat15} />
        </group>
        <group name="group645913543">
          <mesh name="mesh645913543" geometry={nodes.mesh645913543.geometry} material={materials.mat15} />
          <mesh name="mesh645913543_1" geometry={nodes.mesh645913543_1.geometry} material={materials.mat17} />
        </group>
        <group name="group1026807776">
          <mesh name="mesh1026807776" geometry={nodes.mesh1026807776.geometry} material={materials.mat16} />
          <mesh name="mesh1026807776_1" geometry={nodes.mesh1026807776_1.geometry} material={materials.mat17} />
          <mesh name="mesh1026807776_2" geometry={nodes.mesh1026807776_2.geometry} material={materials.mat12} />
        </group>
        <mesh name="group1994619716" geometry={nodes.group1994619716.geometry} material={materials.mat16} />
        <group name="group1591139603">
          <mesh name="mesh1591139603" geometry={nodes.mesh1591139603.geometry} material={materials.mat16} />
          <mesh name="mesh1591139603_1" geometry={nodes.mesh1591139603_1.geometry} material={materials.mat24} />
          <mesh name="mesh1591139603_2" geometry={nodes.mesh1591139603_2.geometry} material={materials.mat12} />
          <mesh name="mesh1591139603_3" geometry={nodes.mesh1591139603_3.geometry} material={materials.mat17} />
        </group>
        <group name="group707679182">
          <mesh name="mesh707679182" geometry={nodes.mesh707679182.geometry} material={materials.mat17} />
          <mesh name="mesh707679182_1" geometry={nodes.mesh707679182_1.geometry} material={materials.mat16} />
          <mesh name="mesh707679182_2" geometry={nodes.mesh707679182_2.geometry} material={materials.mat24} />
          <mesh name="mesh707679182_3" geometry={nodes.mesh707679182_3.geometry} material={materials.mat12} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/VendalWorkshop.glb')
